### PR TITLE
Removing references to whitelist/blacklist.

### PR DESCRIPTION
**Pull request by monkeysecurity**
Removing references to blacklist in code, filenames, and documentation. Moving away from blacklist/whitelist globally and towards blocklist/allowlist.

Those upgrading may need to also update their config. If @mcpeak or @JohnVonNeumann have suggestions for making the update/upgrade work magically, please let me know.

### CODE REVIEW

**Comment by mcpeak** [comment]
@monkeysecurity can you fallback on the old config values, or does that bypass the point?

**Comment by JohnVonNeumann** [comment]
Would it be possible to split the PR's into different contexts? The change in language could be easily merged after the addition of the new feature, it helps keep reviews on point and overall easier to understand. A grep-and-replace PR requires a lot less work on a reviewers part than that of a feature addition review.

**Comment by monkeysecurity** [comment]
I think that's a good idea.  I'll try and work on that tomorrow.

**Comment by monkeysecurity** [comment]
I'll work on the fallback to the old names tomorrow and will update this PR.

Thanks.

**Comment by monkeysecurity** [comment]
The fallback logic works in our test environment. This is ready to be merged.

**Comment by mcpeak** [comment]
Looks good to me

**Pull request merged**
