### PR TITLE
add flake8 to travis ci

### LINKED ISSUE #43: Add Flake8 to TravisCI
It would be nice to have TravisCI check flake8 for the project.  We can ignore the finding about lines longer than 80 (line length limit should be 120).

### PR DESCRIPTION
**Pull request by suprithIUB**
Fixes #43

### CODE REVIEW

**Comment by mcpeak** [comment]
Looks good, but now we're not passing :).  You think it makes sense to fix in this PR or another?

**Comment by suprithIUB** [comment]
Please check now @mcpeak

**Comment by mcpeak** [comment]
Hmm, if I run the flake8 command manually though it gives me a bunch of errors.  Not sure how it's passing...

**Comment by suprithIUB** [comment]
Did you work with the latest commit of mine? Maybe you are missing setup.cfg file?

**Comment by mcpeak** [comment]
Oh, you're right.  It's finding issues in artifacts on my side.  👍  Nice work!

**Pull request merged**
